version: "3.9"

services:

  devcontainer:
    build:
      context: .
      target: dev
      {%- if cookiecutter.private_package_repository_name %}
      secrets:
        - poetry-auth
      {%- endif %}
      args:
        PYTHON_VERSION: ${PYTHON_VERSION:-{{ cookiecutter.python_version }}}
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    {%- if not cookiecutter.private_package_repository_name %}
    environment:
      - POETRY_PYPI_TOKEN_PYPI
    {%- else %}
    secrets:
      - poetry-auth
    {%- endif %}
    volumes:
      - ${WORKSPACE_SOURCE:-.}:${WORKSPACE_TARGET:-/app/{{ cookiecutter.__package_name_kebab_case }}/}
      - command-history-volume:/home/app/.history/

  dev:
    extends: devcontainer
    stdin_open: true
    tty: true
    entrypoint: []
    command:
      [
        "sh",
        "-c",
        "sudo chown app $$SSH_AUTH_SOCK && cp --update /opt/build/poetry/poetry.lock /app/{{ cookiecutter.__package_name_kebab_case }}/ && mkdir -p /app/{{ cookiecutter.__package_name_kebab_case }}/.git/hooks/ && cp --update /opt/build/git/* /app/{{ cookiecutter.__package_name_kebab_case }}/.git/hooks/ && zsh"
      ]
    environment:
      {%- if not cookiecutter.private_package_repository_name %}
      - POETRY_PYPI_TOKEN_PYPI
      {%- endif %}
      - SSH_AUTH_SOCK=/run/host-services/ssh-auth.sock
    {%- if cookiecutter.with_fastapi_api|int or cookiecutter.with_streamlit_app|int %}
    ports:
      - "8000"
    {%- endif %}
    volumes:
      - ~/.gitconfig:/etc/gitconfig
      - ~/.ssh/known_hosts:/home/app/.ssh/known_hosts
      - ${SSH_AGENT_AUTH_SOCK:-/run/host-services/ssh-auth.sock}:/run/host-services/ssh-auth.sock
    profiles:
      - dev
  {%- if cookiecutter.with_fastapi_api|int or cookiecutter.with_streamlit_app|int or cookiecutter.with_typer_cli|int %}

  app:
    build:
      context: .
      target: app
      {%- if cookiecutter.private_package_repository_name %}
      secrets:
        - poetry-auth
      {%- endif %}
    tty: true
    {%- if cookiecutter.with_fastapi_api|int or cookiecutter.with_streamlit_app|int %}
    ports:
      - "8000:8000"
    {%- endif %}
    profiles:
      - app
  {%- endif %}
{%- if cookiecutter.private_package_repository_name %}

secrets:
  poetry-auth:
    file: "${POETRY_AUTH_TOML_PATH:-~/Library/Preferences/pypoetry/auth.toml}"
{%- endif %}

volumes:
  command-history-volume:
  devcontainer-volume:
    name: ${WORKSPACE_CONTAINER_VOLUME_SOURCE:-not-used-in-bind-mount-workspace}
    external: ${WORKSPACE_IS_CONTAINER_VOLUME:-false}
