version: "3.9"

services:
  dev:
    build:
      context: .
      target: dev
      {%- if cookiecutter.private_package_repository_name %}
      secrets:
        - poetry_auth
      {%- endif %}
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    stdin_open: true
    tty: true
    entrypoint: []
    command:
      [
        "sh",
        "-c",
        "cp --update /opt/build/poetry/poetry.lock /app/ && mkdir -p /app/.git/hooks/ && cp --update /opt/build/git/* /app/.git/hooks/ && zsh"
      ]
    environment:
      {%- if not cookiecutter.private_package_repository_name %}
      - POETRY_PYPI_TOKEN_PYPI
      {%- endif %}
      - SSH_AUTH_SOCK=/run/host-services/ssh-auth.sock
    {%- if cookiecutter.with_fastapi_api|int or cookiecutter.with_streamlit_app|int %}
    ports:
      - "8000"
    {%- endif %}
    {%- if cookiecutter.private_package_repository_name %}
    secrets:
      - poetry_auth
    {%- endif %}
    volumes:
      - .:/app/
      - ~/.gitconfig:/etc/gitconfig
      - ~/.ssh/known_hosts:/home/app/.ssh/known_hosts
      - ${SSH_AGENT_AUTH_SOCK:-/run/host-services/ssh-auth.sock}:/run/host-services/ssh-auth.sock
  {%- if cookiecutter.with_fastapi_api|int or cookiecutter.with_streamlit_app|int or cookiecutter.with_typer_cli|int %}
  app:
    build:
      context: .
      target: app
      {%- if cookiecutter.private_package_repository_name %}
      secrets:
        - poetry_auth
      {%- endif %}
    tty: true
    {%- if cookiecutter.with_fastapi_api|int or cookiecutter.with_streamlit_app|int %}
    ports:
      - "8000:8000"
    {%- endif %}
    profiles:
      - app
  {%- endif %}
{%- if cookiecutter.private_package_repository_name %}

secrets:
  poetry_auth:
    file: "${POETRY_AUTH_TOML_PATH:-~/Library/Application Support/pypoetry/auth.toml}"
{%- endif %}
