version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    commit-message:
      prefix: "ci"
      prefix-development: "ci"
      include: scope
    groups:
       ci-dependencies:
          patterns:
            - "*"
{%- if cookiecutter.with_fastapi_api|int or cookiecutter.with_streamlit_app|int or cookiecutter.with_typer_cli|int %}
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: monthly
    commit-message:
      prefix: "chore"
      prefix-development: "build"
      include: scope
    versioning-strategy: increase
    allow:
      - dependency-type: production
    groups:
       runtime-dependencies:
          patterns:
            - "*"
{%- endif %}
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: monthly
    commit-message:
      prefix: "chore"
      prefix-development: "build"
      include: scope
    versioning-strategy: increase
    allow:
      - dependency-type: development
    groups:
       development-dependencies:
          patterns:
            - "*"
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: monthly
    commit-message:
      prefix: "chore"
      prefix-development: "build"
      include: scope
    versioning-strategy: lockfile-only
    allow:
      - dependency-type: indirect
    groups:
       transitive-dependencies:
          patterns:
            - "*"
