name: Test

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:

  test:

    runs-on: ubuntu-latest

    strategy:

      matrix:
        python-version: ["3.8"]
      fail-fast: false

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Cruft and Poetry
        run: pip install --no-input cruft poetry "click<=8.0.4"  # pinned to work around https://github.com/tiangolo/typer/issues/377, change when that is fixed

      - name: Scaffold package
        run: |
          cruft create --no-input --extra-context '{"with_fastapi_api": "1"}' .

      - name: Cache Python environment
        uses: actions/cache@v2
        with:
          path: my-package/.venv
          key: venv-${{ runner.os }}-py${{ matrix.python-version }}-${{ hashFiles('my-package/pyproject.toml') }}

      - name: Install Python environment
        run: |
          git init
          git add .
          poetry config virtualenvs.in-project true
          poetry install --no-interaction
        working-directory: ./my-package

      - name: Lint package
        run: poetry run poe lint
        working-directory: ./my-package

      - name: Test package
        run: poetry run poe test
        working-directory: ./my-package
