# https://pre-commit.com
default_install_hook_types: [commit-msg, pre-commit]
default_stages: [commit, manual]
fail_fast: true
repos:
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.9.0
    hooks:
      - id: python-check-blanket-noqa
      - id: python-check-blanket-type-ignore
      - id: python-check-mock-methods
      - id: python-no-eval
      - id: python-no-log-warn
      - id: python-use-type-annotations
      - id: python-check-blanket-noqa
      - id: rst-backticks
      - id: rst-directive-colons
      - id: rst-inline-touching-normal
      - id: text-unicode-replacement-char
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-json
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-toml
      - id: check-vcs-permalinks
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: detect-private-key
      - id: fix-byte-order-marker
      - id: mixed-line-ending
      - id: trailing-whitespace
        types: [python]
      - id: end-of-file-fixer
        types: [python]
  - repo: local
    hooks:
      - id: commitizen
        name: commitizen
        entry: cz check --commit-msg-file
        require_serial: true
        language: system
        stages: [commit-msg]
      - id: pyupgrade
        name: pyupgrade
        entry: pyupgrade --py{{ cookiecutter.python_version|replace(".", "") }}-plus
        require_serial: true
        language: system
        types: [python]
      - id: isort
        name: isort
        entry: isort
        require_serial: true
        language: system
        types: [python]
      - id: black
        name: black
        entry: black
        require_serial: true
        language: system
        types: [python]
      - id: shellcheck
        name: shellcheck
        entry: shellcheck --check-sourced
        language: system
        types: [shell]
      - id: bandit
        name: bandit
        entry: bandit --configfile pyproject.toml
        language: system
        types: [python]
      - id: pydocstyle
        name: pydocstyle
        entry: pydocstyle
        language: system
        types: [python]
      - id: flake8
        name: flake8
        entry: flake8
        language: system
        types: [python]
      - id: poetry-check
        name: poetry check
        entry: poetry check
        language: system
        files: pyproject.toml
        pass_filenames: false
      - id: mypy
        name: mypy
        entry: mypy
        language: system
        types: [python]
