version: "3.9"

services:
  dev:
    build:
      context: .
      target: dev
      {%- if cookiecutter.private_package_repository_name %}
      secrets:
        - poetry_auth
      {%- endif %}
    tty: true
    entrypoint: []
    command:
      [
        "sh",
        "-c",
        {%- if cookiecutter.private_package_repository_name %}
        "cp --update /var/lib/poetry/poetry.lock /app/ && mkdir -p /app/.git/hooks/ && cp --update /var/lib/git/* /app/.git/hooks/ && ln -s /run/secrets/poetry_auth /root/.config/pypoetry/auth.toml && sleep infinity"
        {%- else %}
        "cp --update /var/lib/poetry/poetry.lock /app/ && mkdir -p /app/.git/hooks/ && cp --update /var/lib/git/* /app/.git/hooks/ && sleep infinity"
        {%- endif %}
      ]
    {%- if not cookiecutter.private_package_repository_name %}
    environment:
      - POETRY_PYPI_TOKEN_PYPI
    {%- endif %}
    {%- if cookiecutter.with_fastapi_api|int or cookiecutter.with_streamlit_app|int %}
    ports:
      - "8000"
    {%- endif %}
    {%- if cookiecutter.private_package_repository_name %}
    secrets:
      - poetry_auth
    {%- endif %}
    volumes:
      - .:/app/:cached
      - app-env:/opt/app-env/
  {%- if cookiecutter.with_fastapi_api|int or cookiecutter.with_streamlit_app|int or cookiecutter.with_typer_cli|int %}
  app:
    build:
      context: .
      target: app
      {%- if cookiecutter.private_package_repository_name %}
      secrets:
        - poetry_auth
      {%- endif %}
    tty: true
    {%- if cookiecutter.with_fastapi_api|int or cookiecutter.with_streamlit_app|int %}
    ports:
      - "8000:8000"
    {%- endif %}
    profiles:
      - app
  {%- endif %}
{%- if cookiecutter.private_package_repository_name %}

secrets:
  poetry_auth:
    file: $POETRY_AUTH_TOML_PATH
{%- endif %}

volumes:
  app-env:
